<a href="https://colab.research.google.com/github/Lyv24/Tarea5_THC/blob/main/Clase_19_de_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Clase 19 de octubre \\
Cruz Contreras Isari Lyvier

In [ ]:
#Numpy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])#lista

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr1 = np.array((1, 2, 3, 4, 5))#tupla

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#arreglo cerodimensional
arr = np.array(42)

print(arr)

42


In [ ]:
#Arreglo bidimensional
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Arreglos tridimensionales
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Dimensiones y shape
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
#matriz(num renglones, num elementos,...)
print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
#Más dimensiones
arr = np.array([1,2,3,4], ndmin=5)

print(arr)

In [ ]:
arr = np.array([1,2,3,4])

print(arr[0])

1


In [ ]:
#Una dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2do elemento de la 1er Fila: ",arr[0,1] )

2do elemento de la 1er Fila:  2


In [ ]:
#Dos dimensiones
print("Tercer elemento de la 2da fila: ",arr[1,2])

Quinto elemento de la 2da fila:  6


In [ ]:
#Tres dimensiones
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr[1,0,1] )

2


In [ ]:
#Para listas
def matrices_sum(A,B,C):
  if len(A)==len(B)==len(C):
      n=len(A)
      H=n*[1.1]
      D=0
      for i in range (n):
        H[i]=A[i]+B[i]+C[i]
        D=H[i]+D
      print(D)
  else:
    print(NO)
matrices_sum(A=[1,1,1],B=[1,1,1],C=[1,1,1])

9


In [ ]:
#Para arreglos
arr = np.array([[1,1,1],[1,1,1],[1,1,1]])
D=0
for i in range(len(arr)):
  for j in range(len(arr)):
    D=D+arr[i,j]
print(D)



9


In [ ]:
#Para listas
def producto_punto(A,B):
  if len(A)==len(B):
      n=len(A)
      C=n*[1.1]
      D=0
      for i in range (n):
        C[i]=A[i]*B[i]
        D=C[i]+D
      print(D)
  else:
    print(NO)
producto_punto(A=[1,1,1],B=[1,1,1])

3


In [ ]:
def Prod_punto(a,b):
  for i in range(len(a)):
    PP=0.0
    PP=a[i]*b[i]
  return PP

In [ ]:
arr2 = np.array([[1,1,1],[1,1,1],[1,1,1]])
arr3 = np.array([[1,1,1],[1,1,1],[1,1,1]])
Pp_por_reng=np.array([0,0,0])
Pp_por_column=np.array([0,0,0])

for i in range(len(arr2)):
  Pp_por_reng[i]=Prod_punto(arr2[i],arr3[i])

Pp_por_reng

array([1, 1, 1])

In [ ]:
def AgarraCol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])

  return np.array(nuevo)
col1=AgarraCol(arr2,0)
col1

array([1, 1, 1])

In [ ]:
for i in range(len(arr2)):
  Pp_por_column[i]=Prod_punto(AgarraCol(arr2,i),AgarraCol(arr3,i))
Pp_por_column

array([1, 1, 1])

In [ ]:
def producto_escalar(n,A,B):
  c=len(A)
  B=c*[1.1]
  for i in range (c):
    B[i]=n*A[i]
  print(B)

producto_escalar(3,A=[1,1,1],B=[1,1,1])

[3, 3, 3]


In [ ]:
arr1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
D=3
C=[]
for i in range(len(arr1)):
  for j in range (len(arr1[i])):
    D=D*arr1[i,j]
    print(D)



3
3
3
3
3
3
3
3
3
